# Generated by Django 4.2.4 on 2023-10-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lists',
            name='position',
            field=models.IntegerField(default=1),
        ),
    ]
