# Generated by Django 4.2.4 on 2023-10-27 08:46

import boards.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boards',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to=boards.models.Boards.board_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
