# Generated by Django 4.2.4 on 2023-10-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='position',
            field=models.IntegerField(default=1),
        ),
    ]
